### ISSUE TITLE
cant play a.mp4

### ISSUE THREAD

**Issue by solodoit** [baka3k/RTSPRecorder#2]
When I used the video recording function, the a.mp4  file generated did not play. so I went to make sure I had given all permissions

https://user-images.githubusercontent.com/8099847/220508254-8b269b3f-8eae-4eb4-81d9-8de8a313bd64.mp4

**Comment by baka3k** [comment]
@solodoit : please make sure that you always invoke stopRecord() - if missing it - your video will be broken and can not play

**Comment by solodoit** [comment]
> @solodoit : please make sure that you always invoke stopRecord() - if missing it - your video will be broken and can not play

Im sure stopRecord()，have the long toast.

**Comment by baka3k** [comment]
Let me confirm some points:
+ how about default url? (rtsp://wowzaec2demo.streamlock.net/vod/mp4)
looks like you used on a custom rtsp server? I'm not sure about your rtsp server 
Could you check it again?

**Comment by solodoit** [comment]
> Let me confirm some points:
> 
> * how about default url? (rtsp://wowzaec2demo.streamlock.net/vod/mp4)
>   looks like you used on a custom rtsp server? I'm not sure about your rtsp server
>   Could you check it again?

default url is OK, The following file is my log。
[log.txt](https://github.com/baka3k/RTSPRecorder/files/10849349/log.txt)

**Comment by baka3k** [comment]
In your log, just has play/start video streaming information, i could not find error related record function
could you share me your sample app( your rtsp server )?

**Comment by solodoit** [comment]
> 
I'm sorry, but my server is in my drone, so I can't provide it.

**Comment by solodoit** [comment]
> Server run on android device? I just want apk(can install on android device) or source code sample

I just downloaded the code for the project and changed the URL to my own server running on an embedded system, I'm not sure exactly

**Comment by baka3k** [comment]
Oh, It's hard to judge, because I don't know the protocol/message or the codec are used in your server
and also can not reproduce your issue on my environment

**Comment by solodoit** [comment]
> Oh, It's hard to judge, because I don't know the protocol/message or the codec are used in your server and also can not reproduce your issue on my environment

Thank you very much for your time and patience to troubleshoot the problem

**Comment by baka3k** [comment]
you are welcome!
